### ISSUE TITLE
substitute highlighting no longer works until after replacement

### ISSUE THREAD

**Issue by kirjavascript** [markonm/traces.vim#17]
video: https://gfycat.com/FarflungBlondFlea

**Comment by markonm** [comment]
Please provide Vim and plugin versions and minimal vimrc.

**Comment by kirjavascript** [comment]
ah, that should've been the first thing I checked

after breaking down a minimal vimrc I discovered that it's due to interactions with this plugin: https://github.com/itchyny/lightline.vim - simply  loading both causes the issue

if you don't support this kind of issue it can be closed, thanks

**Comment by markonm** [comment]
It should be fixed now for vim versions 8.0.1445+. For some reason the change slows down highlighting on older versions, so I disabled it there. Please test.

**Comment by kirjavascript** [comment]
can confirm it works now, thanks a lot!

**Comment by markonm** [comment]
You’re welcome.
