### ISSUE TITLE
spaces replaced by line break in preview if regex syntax specified in :substitute

### ISSUE THREAD

**Issue by Konfekt** [markonm/traces.vim#21]
In any archive, hitting
```vim
:%substitute:\v::cgI<Left><Left><Left><Left><Left>
```
inserts line breaks where spaces are. Same for any other regular expression syntax modifier, such as `\m` or `\V`.

**Comment by markonm** [comment]
Is soft wrapping enabled when it happens?

**Comment by Konfekt** [comment]
Yes.

**Comment by markonm** [comment]
Do you have the same issue when it's turned off?

**Comment by Konfekt** [comment]
No.

**Comment by markonm** [comment]
This issue is then a duplicate of #18.  Closing.
