### ISSUE TITLE
Traces.vim breaks backspace in second column in commandline mode

### ISSUE THREAD

**Issue by bstaletic** [markonm/traces.vim#22]
Hello,

I've found an odd behaviour which seems to be related to traces.vim.

Steps to reproduce:

- Open `vim`
- Type `:g/foo` or any other command that traces.vim has an effect on. (`:s`, `:v`)
- Move the cursor over `/`.
- Press `<BS>`

Expected behaviour (`<CURSOR>` denotes cursor position): `:<CURSOR>/foo`.
Actual behaviour: `:/<CURSOR>foo`.

The reason I believe this is caused by traces.vim is because removing it made the unexpected cursor movement go away.

**Comment by markonm** [comment]
That's caused by   https://github.com/markonm/traces.vim/blob/master/autoload/traces.vim#L1078-L1081. Could you try removing it? If I remember correctly it was attempt to fix https://github.com/vim/vim/issues/2612 which caused faulty highlight or invisible cursor.

**Comment by bstaletic** [comment]
Commenting out the whole `if` block solved the wrong cursor move, but it did cause my cursor to get invisible, just like you mentioned.

**Comment by markonm** [comment]
I'll push a commit to flip movement when cursor is at the start of command line. Sadly, I cannot think of another workaround.

**Comment by bstaletic** [comment]
Another workaround would be just doing `<Left>` when at the beginning of the line. `<Down>` works if the user didn't attempt to scroll through commandline history.

Workarounds are annoying...

**Comment by bstaletic** [comment]
Thanks!

**Comment by markonm** [comment]
You're welcome. Thanks for reporting the issue..
