### ISSUE TITLE
Preview split

### ISSUE THREAD

**Issue by lunacookies** [markonm/traces.vim#24]
Is it possible to make a split display upon starting a substitution showing matches and replacements, akin to `set inccomand=split` in NeoVim? Thanks.

**Comment by markonm** [comment]
It is not possible currently.

**Comment by ght** [comment]
Thank you for making me find out about [`inccommand`](https://neovim.io/doc/user/options.html#'inccommand')!

Does this plugin have any features/advantages over that, apart from not being Nvim-only? If so, please briefly mention those in the part in the README that mentions that the two are not compatible.

**Comment by markonm** [comment]
@ght I added a feature comparison to README.

**Comment by ght** [comment]
Nice, that is just what I had in mind! (linking 46c02cde67 which adds the comparison, just so the discussed changes can easily be found in the future)

**Comment by markonm** [comment]
> 
> 
> Is it possible to make a split display upon starting a substitution showing matches and replacements, akin to `set inccomand=split` in NeoVim? Thanks.

It's possible from now on. In case you are still interested, to emulate `set inccomand=split` behavior add the following to your vimrc.
```
let g:traces_preview_window="botright 7new"
```
