### ISSUE TITLE
Highlight when range is whole file.

### ISSUE THREAD

**Issue by ErikLambrechts** [markonm/traces.vim#3]
Is it possible to skip the range highlight is the hole file, using `%`? 

Could this be done by adding a condition at https://github.com/xtal8/traces.vim/blob/cb67127f0735118bfdda22ce977a3b75077bc561/plugin/traces.vim#L135

**Comment by markonm** [comment]
Yes, it's possible. I added an option. Use  `let g:traces_whole_file_range = 0` to disable highlighting for `%` specifier.

**Comment by ErikLambrechts** [comment]
awesome
