### ISSUE TITLE
feature request: change highlighting color

### ISSUE THREAD

**Issue by davemachado** [markonm/traces.vim#34]
Hi, this plugin is super great! Unfortunately I use a dark theme terminal and the bright yellow highlighting makes it impossible to read the light-colored text. It would be so great if the highlighting color was configurable!

**Comment by markonm** [comment]
What color scheme do you use? You can already use `TracesSearch` highlight group to change pattern highlighting. Try adding the following to your vimrc:
```
hi link TracesSearch WildMenu
```

**Comment by davemachado** [comment]
I was able to get a new color selected by adding the following to my vimrc:
```
set hlsearch
hi Search ctermbg=LightYellow
hi Search ctermfg=Red
```
Thanks!
