### ISSUE TITLE
Substitution preview doesn't show when the substitution string is blank

### ISSUE THREAD

**Issue by novadev94** [markonm/traces.vim#35]
I think a screen capture would describe it in the easiest way :D

![image](https://user-images.githubusercontent.com/6073918/75332519-1d2d7800-58b7-11ea-857b-376facf6e5e4.png)

**Comment by novadev94** [comment]
After some searching, I found this: https://github.com/markonm/traces.vim/commit/2bfc63174002903e350de418006eea83efcc8901

I'm just curious about how the decision was made back then.

**Comment by markonm** [comment]
The reasoning behind the commit was to allow one to see matched text while using mappings such as `nnoremap gss :%s/\<<c-r><c-w>\>//g<left><left>`. Previewing empty string seems less useful in comparison.

**Comment by novadev94** [comment]
Thanks!

**Comment by lkintact** [comment]
@markonm Maybe that behaviour should be made configurable via a variable?
