### ISSUE TITLE
Not able to get it to work using vim-plug.

### ISSUE THREAD

**Issue by TanishBansal** [markonm/traces.vim#37]
Used vim-plug to install.

▶vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan 12 2017 04:34:55)
Included patches: 1-172
 

Is there something that I am missing.

**Comment by markonm** [comment]
Your Vim is too old. This plugin supports Vim v8.0.1206 and later.

**Comment by TanishBansal** [comment]
It's 8.0.172, is that older than 8.0.1206?

**Comment by markonm** [comment]
Yes. Your vim includes patches 1-172, whereas this plugin requires patches 1-1206. 

I agree, it is confusing to request specific patch levels. I'll amend docs and indicate only major.minor version requirements.
