### ISSUE TITLE
Support for vim-abolish's substitution

### ISSUE THREAD

**Issue by fnune** [markonm/traces.vim#41]
https://github.com/tpope/vim-abolish#substitution

With vim-abolish, instead of this:

```
:%s/facility/building/g
:%s/Facility/Building/g
:%s/FACILITY/BUILDING/g
:%s/facilities/buildings/g
:%s/Facilities/Buildings/g
:%s/FACILITIES/BUILDINGS/g
```

You can do this:

```
:%Subvert/facilit{y,ies}/building{,s}/g
```

I think if traces.vim supported previews for this, it would be amazing!

**Comment by markonm** [comment]
It is already supported. Add the following to your vimrc to enable the preview:
```vim
let g:traces_abolish_integration = 1
```

**Comment by fnune** [comment]
Oh! It's literally the last commit! So cool. Thank you!
