### ISSUE TITLE
Setting 'linebreak' messes up highlighting

### ISSUE THREAD

**Issue by lkintact** [markonm/traces.vim#47]
1. Run `gvim.exe --clean classes.txt` [classes.txt](https://github.com/user-attachments/files/15571660/classes.txt)
2. Execute `:packadd traces.vim-master`
3. Execute `:set linebreak`
4. Type `:%s/, /./g`. You should see something like this (note the region with incorrect highlighting outlined in red):

![incorrect_highlighting](https://github.com/markonm/traces.vim/assets/24726299/a60ce38f-4906-4d98-98d2-d33055b3f61a)
 

Vim 9.1.443
Traces 1.1.0.

**Comment by markonm** [comment]
This is related to #18. I don't know how to fix it.

**Comment by lkintact** [comment]
Thanks for letting know anyway, your plugin is of much help!
