### ISSUE TITLE
Turning the highlight off?

### ISSUE THREAD

**Issue by for-coursera** [markonm/traces.vim#7]
What about adding the possibility to automatically turn the highlight off after an operation is completed (like, if substitute command was performed on a range – it still highlights search patterns outside the range then), or if the cursor was moved after a search (surely, that should exclude `n/N` movements)?

**Comment by markonm** [comment]
Are you talking about native `hlsearch` highlighting? The plugin currently disables `hlsearch` when highlighting patterns and returns it to prior state when exiting command line. `hlsearch` is not necessary for this plugin's behavior and can be switched off at all time.

**Comment by for-coursera** [comment]
I see. And this plugin also doesn't affect the usual search (`/`/`?`) at all? Works only with `:` commands?

**Comment by markonm** [comment]
The plugin is only active inside `:` mode. It does not change value of `/` register. The actual command you execute from `:` mode will change the value of `/` register and consequently what `hlsearch` highlights, but that is standard Vim behavior.
